### ISSUE TITLE
Does upload require full path? Or just a name?

### ISSUE THREAD

**Issue by teknolojia** [benawad/apollo-upload-example#1]
I am following your youtube video on image uploading. But there is something confuses me!
```
lastModified: 1557260045683
​
name: "vlcsnap-2019-05-07-23h14m05s681.png"
​
path: "vlcsnap-2019-05-07-23h14m05s681.png"
​
size: 651948
​
type: "image/png"
​
webkitRelativePath: ""
```
Above is the log of file. I dont see full path of image file I am trying to upload. Will it work with just a name.

**Comment by benawad** [comment]
yeah I think that's a hidden property
